namespace RunesWebScraping.domain
{
    public class RunesParseTable
    {
        public static readonly Dictionary<string, int> table =
            new()
            {
                { "Precision", 8000 },
                { "Domination", 8100 },
                { "Sorcery", 8200 },
                { "Inspiration", 8300 },
                { "Resolve", 8400 },
                { "Electrocute", 8112 },
                { "The Elegant Duelist", 8344 },
                { "Predator", 8124 },
                { "Dark Harvest", 8128 },
                { "The Twisted Surgeon", 8127 },
                { "The Calamity", 8220 },
                { "The Merciless Elite", 8016 },
                { "The Timeless", 8320 },
                { "The Behemoth", 8414 },
                { "Hail of Blades", 9923 },
                { "Glacial Augment", 8351 },
                { "The Arcane Colossus", 8415 },
                { "The Enlightened Titan", 8416 },
                { "Unsealed Spellbook", 8360 },
                { "Iron Skin", 8430 },
                { "First Strike", 8369 },
                { "Press the Attack", 8005 },
                { "The Brazen Perfect", 8004 },
                { "The Immortal Butcher", 8114 },
                { "Lethal Tempo", 8008 },
                { "Fleet Footwork", 8021 },
                { "Conqueror", 8010 },
                { "Triple Tonic", 8313 },
                { "Grasp of the Undying", 8437 },
                { "Aftershock", 8439 },
                { "Guardian", 8465 },
                { "Summon Aery", 8214 },
                { "Arcane Comet", 8229 },
                { "Phase Rush", 8230 },
                { "Cheap Shot", 8126 },
                { "The Aether Blade", 8115 },
                { "The Ruthless Visionary", 8318 },
                { "Kleptomancy", 8359 },
                { "The Wicked Maestro", 8109 },
                { "The Ancient One", 8208 },
                { "Taste of Blood", 8139 },
                { "Sudden Impact", 8143 },
                { "Zombie Ward", 8136 },
                { "Ghost Poro", 8120 },
                { "Eyeball Collection", 8138 },
                { "Treasure Hunter", 8135 },
                { "Ingenious Hunter", 8134 },
                { "Relentless Hunter", 8105 },
                { "Ultimate Hunter", 8106 },
                { "Hextech Flashtraption", 8306 },
                { "Magical Footwear", 8304 },
                { "Perfect Timing", 8313 },
                { "The Stargazer", 8319 },
                { "Future's Market", 8321 },
                { "Minion Dematerializer", 8316 },
                { "Mirror Shell", 8435 },
                { "Biscuit Delivery", 8345 },
                { "Cosmic Insight", 8347 },
                { "Approach Velocity", 8410 },
                { "Time Warp Tonic", 8352 },
                { "Overheal", 9101 },
                { "Triumph", 9111 },
                { "Presence of Mind", 8009 },
                { "Legend: Alacrity", 9104 },
                { "Legend: Tenacity", 9105 },
                { "Legend: Bloodline", 9103 },
                { "Coup de Grace", 8014 },
                { "Cut Down", 8017 },
                { "Last Stand", 8299 },
                { "Demolish", 8446 },
                { "Font of Life", 8463 },
                { "Shield Bash", 8401 },
                { "Conditioning", 8429 },
                { "Second Wind", 8444 },
                { "Bone Plating", 8473 },
                { "Overgrowth", 8451 },
                { "The Incontestable Spellslinger", 8205 },
                { "The Leviathan", 8454 },
                { "Revitalize", 8453 },
                { "Unflinching", 8242 },
                { "Nullifying Orb", 8224 },
                { "The Eternal Champion", 8006 },
                { "The Savant", 8007 },
                { "Manaflow Band", 8226 },
                { "Nimbus Cloak", 8275 },
                { "Chrysalis", 8472 },
                { "The Cryptic", 8207 },
                { "Transcendence", 8210 },
                { "Resist Scaling", 5012 },
                { "Celerity", 8234 },
                { "Celestial Body", 8339 },
                { "Absolute Focus", 8233 },
                { "Scorch", 8237 },
                { "Waterwalking", 8232 },
                { "Gathering Storm", 8236 },
                { "Adaptive Force", 5008 },
                { "Attack Speed", 5005 },
                { "Ability Haste", 5007 },
                { "Armor", 5002 },
                { "Health Scaling", 5001 },
                { "Magic Resist", 5003 },
                { "Health", 5011 },
                { "Move Speed", 5010 },
                { "Tenacity and Slow Resist", 5013 },
            };
    }
}
